#version 450

#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_buffer_reference : require

// 粒子结构体定义
struct Particle
{
    vec2 pos;
    vec2 vel;
    vec4 gradientPos;
};

// 统一缓冲区结构体定义
struct UBO 
{
    float deltaT;
    float destX;
    float destY;
    int particleCount;
};

// 使用 buffer_reference 定义粒子数组引用类型
layout(buffer_reference, scalar) buffer ParticleArray {
    Particle particles[];
};

// 使用 buffer_reference 定义 UBO 引用类型
layout(buffer_reference, scalar) readonly buffer UBORef {
    UBO ubo;
};

// 推送常量，包含缓冲区地址
layout(push_constant) uniform PushConstants {
    ParticleArray particlesReference;
    UBORef uniformReference;
} pushConstants;

layout (local_size_x = 256) in;

vec2 attraction(vec2 pos, vec2 attractPos) 
{
    vec2 delta = attractPos - pos;
    const float damp = 0.5;
    float dDampedDot = dot(delta, delta) + damp;
    float invDist = 1.0f / sqrt(dDampedDot);
    float invDistCubed = invDist*invDist*invDist;
    return delta * invDistCubed * 0.0035;
}

vec2 repulsion(vec2 pos, vec2 attractPos)
{
    vec2 delta = attractPos - pos;
    float targetDistance = sqrt(dot(delta, delta));
    return delta * (1.0 / (targetDistance * targetDistance * targetDistance)) * -0.000035;
}

void main() 
{
    // 当前 SSBO 索引
    uint index = gl_GlobalInvocationID.x;
    
    // 通过引用访问 UBO 数据
    UBO ubo = pushConstants.uniformReference.ubo;
    
    // 不要尝试写入超出粒子数量的部分
    if (index >= ubo.particleCount) 
        return;    

    // 通过引用读取位置和速度
    vec2 vVel = pushConstants.particlesReference.particles[index].vel.xy;
    vec2 vPos = pushConstants.particlesReference.particles[index].pos.xy;

    vec2 destPos = vec2(ubo.destX, ubo.destY);

    vec2 delta = destPos - vPos;
    float targetDistance = sqrt(dot(delta, delta));
    vVel += repulsion(vPos, destPos.xy) * 0.05;

    // 根据速度移动
    vPos += vVel * ubo.deltaT;

    // 与边界碰撞
    if ((vPos.x < -1.0) || (vPos.x > 1.0) || (vPos.y < -1.0) || (vPos.y > 1.0))
        vVel = (-vVel * 0.1) + attraction(vPos, destPos) * 12;
    else
        pushConstants.particlesReference.particles[index].pos.xy = vPos;

    // 写回
    pushConstants.particlesReference.particles[index].vel.xy = vVel;
    pushConstants.particlesReference.particles[index].gradientPos.x += 0.02 * ubo.deltaT;
    if (pushConstants.particlesReference.particles[index].gradientPos.x > 1.0)
        pushConstants.particlesReference.particles[index].gradientPos.x -= 1.0;
}