#version 450
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_scalar_block_layout : require

struct Particle
{
	vec2 pos;
	vec2 vel;
	vec4 gradientPos;
};

// 使用 bindless 方式声明存储缓冲区数组
layout(std140, binding = 0) buffer Pos 
{
   Particle particles[ ];
} particleBuffers[];  // 声明为数组

layout (local_size_x = 256) in;

layout (binding = 1) uniform UBO 
{
	float deltaT;
	float destX;
	float destY;
	int particleCount;
    uint bufferIndex;  // 添加一个索引来指定使用哪个缓冲区
} ubo;

vec2 attraction(vec2 pos, vec2 attractPos) 
{
    vec2 delta = attractPos - pos;
	const float damp = 0.5;
    float dDampedDot = dot(delta, delta) + damp;
    float invDist = 1.0f / sqrt(dDampedDot);
    float invDistCubed = invDist*invDist*invDist;
    return delta * invDistCubed * 0.0035;
}

vec2 repulsion(vec2 pos, vec2 attractPos)
{
	vec2 delta = attractPos - pos;
	float targetDistance = sqrt(dot(delta, delta));
	return delta * (1.0 / (targetDistance * targetDistance * targetDistance)) * -0.000035;
}

void main() 
{
    // Current SSBO index
    uint index = gl_GlobalInvocationID.x;
	// Don't try to write beyond particle count
    if (index >= ubo.particleCount) 
		return;	

    // 使用 bufferIndex 访问特定的存储缓冲区
    // 读取位置和速度
    vec2 vVel = particleBuffers[ubo.bufferIndex].particles[index].vel.xy;
    vec2 vPos = particleBuffers[ubo.bufferIndex].particles[index].pos.xy;

    vec2 destPos = vec2(ubo.destX, ubo.destY);

    vec2 delta = destPos - vPos;
    float targetDistance = sqrt(dot(delta, delta));
    vVel += repulsion(vPos, destPos.xy) * 0.05;

    // Move by velocity
    vPos += vVel * ubo.deltaT;

    // collide with boundary
    if ((vPos.x < -1.0) || (vPos.x > 1.0) || (vPos.y < -1.0) || (vPos.y > 1.0))
    	vVel = (-vVel * 0.1) + attraction(vPos, destPos) * 12;
    else
    	particleBuffers[ubo.bufferIndex].particles[index].pos.xy = vPos;

    // Write back
    particleBuffers[ubo.bufferIndex].particles[index].vel.xy = vVel;
	particleBuffers[ubo.bufferIndex].particles[index].gradientPos.x += 0.02 * ubo.deltaT;
	if (particleBuffers[ubo.bufferIndex].particles[index].gradientPos.x > 1.0)
        particleBuffers[ubo.bufferIndex].particles[index].gradientPos.x -= 1.0;
}