#version 430

layout(std430, binding = 0) buffer VecA {
	float A[ ];
};

layout(std430, binding = 1) buffer VecB {
	float B[ ];
};

layout(std430, binding = 2) buffer VecC {
	float C[ ];
};

layout(std140, binding = 3) uniform UBOParameters
{
  float k;
  float value;
} ubo;

layout (push_constant) uniform PushConsts {
	uint count;
} pushConsts;

layout (local_size_x = 128) in;

void main() 
{
	uvec3 id = gl_GlobalInvocationID; 

	uint index = id.x;
	if (index >= pushConsts.count) 
		return;
	if (index % 3 == 0) {
		C[index] = A[index];
		A[index] = A[index] + ubo.k;
	} else if (index % 3 == 1) {
		C[index] = B[index];
		B[index] = B[index] - 1.0f;
	} else {
		C[index] = ubo.value;
	}

}